FROM node:20-alpine

WORKDIR /app

COPY vite-project/package*.json ./

RUN npm install

COPY vite-project/ .

RUN npm run build

RUN npm install -g serve

EXPOSE 5173
CMD ["serve", "-s", "dist", "-l", "5173"]
